### ISSUE TITLE
Unable to connect!

### ISSUE THREAD

**Issue by chevdor** [thingsSDK/thingssdk-espruino-strategy#12]
The connection fails and complains:
```
espruino:  Connecting to '/dev/cu.SLAB_USBtoUART'
espruino:  Port "/dev/cu.SLAB_USBtoUART" not found
```

However, nothing should prevent it to connect
```
$ ll /dev/cu.SLAB_USBtoUART 
crw-rw-rw-  1 root  wheel   13,  15 Aug 29 10:18 /dev/cu.SLAB_USBtoUART
```

**Comment by chevdor** [comment]
I initially reported the issue in https://github.com/thingsSDK/thingssdk-cli/issues/44 but I think the problem is in this repo or in the espruino lib.

**Comment by chevdor** [comment]
I should add that the Espruino IDE has no problem to connect with the same port and same speed.

**Comment by chalkers** [comment]
Please upgrade the `thingssdk-espruino-strategy` to version `1.0.3`
