### ISSUE TITLE
Trouble when running  "npm run dev"

### ISSUE THREAD

**Issue by Lysandroc** [thingsSDK/thingssdk-espruino-strategy#13]
Hi, 

I've created a new scaffold to espruino, but it's not working as should. I saw in the code using espruino dependency and its very out of date.

When I use Espreuino Web IDE its working perfectly. 

<img width="947" alt="screen shot 2017-12-03 at 00 14 35" src="https://user-images.githubusercontent.com/8335018/33522017-f2746994-d7c0-11e7-8830-f353d63d8929.png">

{
  "name": "newScaffold",
  "version": "0.0.0",
  "private": true,
  "main": "main.js",
  "scripts": {
    "dev": "node ./scripts/upload development && npm run repl",
    "deploy": "node ./scripts/upload production",
    "repl": "node ./scripts/repl"
  },
  "devDependencies": {
    "thingssdk-deployer": "~1.0.1",
    "thingssdk-espruino-strategy": "~1.0.2"
  }
}

**Comment by chalkers** [comment]
What device are you using? Also did you disconnect the Web IDE?

what happens when you run the command `thingssdk devices`?

**Comment by Lysandroc** [comment]
I'm using nodemcu in the port `/dev/cu.wchusbserial1420`, I've closed the Web IDE, also disconnected and connected the device.  

$ thingssdk devices
? Select a port: (Use arrow keys)
 /dev/cu.Bluetooth-Incoming-Port
  /dev/cu.SamsungLevelover-SPPDev
❯  /dev/cu.wchusbserial1410

After that is generate a devices.json with the following...

`{"devices": {
    "/dev/cu.wchusbserial1420": {
      "baud_rate": 115200,
      "runtime": "espruino"
    }
  }
}`

I've run espruino separately and throw an error too.
`$ espruino -p /dev/cu.wchusbserial1420 mainES5.js`

Espruino Command-line Tool 0.0.33
Connecting to '/dev/cu.wchusbserial1420'
Port "/dev/cu.wchusbserial1420" not found
Unable to connect!

**Comment by chalkers** [comment]
We piggy back on espruino's command-line tool. We froze the version, you could attempt to update to a newer Espruino version. Try that out and see if that helps or not?

**Comment by chevdor** [comment]
Check this one out: https://github.com/thingsSDK/thingssdk-cli/issues/45#issuecomment-356898397
I think it is related

**Comment by chalkers** [comment]
Sorry for delay. I've updated the `thingssdk-espruino-strategy` to use the latest Espruino CLI.

You also need a postinstall script for the package.json like so `"postinstall": "rimraf node_modules/bluetooth-hci-socket"`.

Please upgrade your package.json to include the `thingssdk-espruino-strategy` to `~1.0.3`.

Also, please upgrade globally `thingssdk-cli` to `1.3.0`.

Currently the ESP32 isn't 'supported' but it may work :)

Your package.json should look like this:

```
{
  "name": "sampleproject",
  "version": "0.0.0",
  "private": true,
  "main": "main.js",
  "scripts": {
    "dev": "node ./scripts/upload development && npm run repl",
    "deploy": "node ./scripts/upload production",
    "repl": "node ./scripts/repl",
    "postinstall": "rimraf node_modules/bluetooth-hci-socket"
  },
  "devDependencies": {
    "thingssdk-deployer": "~1.0.1",
    "thingssdk-espruino-strategy": "~1.0.3"
  }
}
```
